### ISSUE TITLE
Nan values with color picker

### ISSUE THREAD

**Issue by mentasuave01** [GoogleChromeLabs/ProjectVisBug#618] opened 2024-04-04 08:33 UTC
https://github.com/GoogleChromeLabs/ProjectVisBug/assets/60361959/a8668fb2-8eec-4304-8cac-6df521ceadba

**Comment by argyleink** [comment] 2024-04-04 18:10
thanks for reporting!

very strange that 1 of the 3 RGB channels is NaN… VisBug takes the color from the color picker and doesnt do any transforms on it since it's already a hex value. to me, this bug smells like an issue with the input type color element in your browser version. Will you go to this Codepen and see if it happens against a non-visbug controlled color picker? https://codepen.io/argyleink/pen/GRLQqGR

i'm hoping the issue reproduces there, at which point, I can help you log an issue on Chromium's bug tracker. speaking of which, what's your browser version and OS?

**Comment by mentasuave01** [comment] 2024-04-05 06:56
Codepen is working properly.

Browsers where I have the issue:
Brave [Version 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)](https://brave.com/latest/)
Chrome Version 123.0.6312.86 (Official Build) (64-bit)

OS:
Ubuntu 22.04
.

**Comment by argyleink** [comment] 2024-04-05 15:50
Found the Chromium issue https://g-issues.chromium.org/issues/40777177, doesn't appear there's a fix afaict.. but going to close this, as it's not a VisBug related issue, there's something deeper going on with the eyedropper.

**Closed by argyleink** 2024-04-05 15:50 UTC
