### ISSUE TITLE
Add Hex code option

### ISSUE THREAD

**Issue by jessandress** [GoogleChromeLabs/ProjectVisBug#286] opened 2019-02-05 15:55 UTC
As a designer I use hex codes way more than hsl for color - could this be added possibly?

**Comment by argyleink** [comment] 2019-02-06 06:37
for sure! i'm trying to figure out the best ux path for changing it. should it be an extension setting through like an extension flyout, or just something you do while using the inspector? what ways do you think sound nice to change the display setting/type of your color values in the inspector?

btw, you can get the hex value from the color picker under the toolbar 
![screen shot 2019-02-05 at 10 34 49 pm](https://user-images.githubusercontent.com/1134620/52324481-4c183980-2996-11e9-9b78-289b55d79c74.png)

dupe of #221

**Closed by argyleink** 2019-02-06 06:37 UTC
