### ISSUE TITLE
Color picking needs improvements 

### ISSUE THREAD

**Issue by Costas-Zeimpekis** [GoogleChromeLabs/ProjectVisBug#424] opened 2019-12-19 09:31 UTC
OS windows 10
When I choose an element the color that is already set does not appear on the color panel
When I change color that should change the element in real time, so I do not need to set the color see if it is the one I like and if not go trough the process again

**Comment by argyleink** [comment] 2019-12-27 19:04
I agree, the behavior you describe is the intended behavior of the tool. Can you share more details about when and where this is happening to you? I did some testing on my windows machine, and here's my report:

<br>

> 1. when selecting something on the page, the color picker should update and show the text color, background color and border color (unless it's an svg, which it then shows fill, stroke, etc)

I wasn't able to reproduce this issue on windows. the elements I clicked on properly updated the color panel swatches with the respective color. Are there specific types of things you're selecting? VisBug does show a transparent color if nothing is set for that element.

<br>

> 2. when an item is selected and I'm selecting a new color via the picker, the element should update without needing to confirm the color

unfortunately this is a problem with the color picker input element on windows chromium. this problem does not exists on mac builds of chromium. there is active work happening on the color input, so there's a decent potential this issue get's resolved with that element update. essentially the bug is that the input element isn't emitting a change event, so visbug isn't being told there's a new color until the user presses the confirmation button in the popup. 😢  visbug prefers to lean on the system elements so the experience feels native. i'm not sure how other apps get around this ux issue 🤷‍♂ 

color picker on edge (proof of active work happening):
![color-picker-edge](https://user-images.githubusercontent.com/1134620/71529167-3787ad00-2898-11ea-9b13-35b638084dd4.PNG)

color picker on chrome: 
![color-picker-chrome](https://user-images.githubusercontent.com/1134620/71529168-38204380-2898-11ea-8e4b-57afff76198c.PNG)

**Comment by argyleink** [comment] 2020-04-14 05:10
curious if this is still happening?

**Closed** 2020-09-01 16:45 UTC
Labels: ¿ question ?, 🐜 bug, 🗣 conversation
