### ISSUE TITLE
APCA inspector invalid result?

### ISSUE THREAD

**Issue by villepreux** [GoogleChromeLabs/ProjectVisBug#626] opened 2024-06-04 11:52 UTC
The accessibility and color-contrast inspector gives me a "not good" feedback regarding APCA contrast in cases where chrome devtools or other contrast checkers give a positive result 

Example : 
  * Front/text color: #22ccee
  * Back color: #101012 
  * Font size: 18px
  * Font weight: 600
  
![image](https://github.com/GoogleChromeLabs/ProjectVisBug/assets/10603009/95095d5f-9d18-4b6a-92d1-6816ba620469)

![image](https://github.com/GoogleChromeLabs/ProjectVisBug/assets/10603009/ed397bd9-3eec-4844-b32d-075d3a2ec731)

**Comment by argyleink** [comment] 2024-06-05 08:03
hi! thanks for reporting and checking in.

last I checked the Chrome DevTools version is using an old version of APCA, VisBug is up to date. I believe this explains the difference between DevTools apca results and visbug's.

regarding the line in the color picker, that's only for WCAG2, which we can see passing in VisBug and devtools.

I don't believe this is a bug, it's mostly that there's been multiple versions of APCA (naturally as it is evolving) and you're running into different versions of it in the wild. If you think i'm missed something, go ahead and reopen this, otherwise I'm going to close it for now as "not a bug".

**Closed by argyleink** 2024-06-05 08:03 UTC
