### ISSUE TITLE
Refresh needed to show & hide extension - Safari and Chrome Extensions

### ISSUE THREAD

**Issue by JDBem** [GoogleChromeLabs/ProjectVisBug#471] opened 2020-11-11 12:34 UTC
Hey,

First of all, what an awesome extension! 

I'm having an issue where I have to refresh the page in order to show and hide the extension. This is happening on both Safari and Chrome.

Hopefully, the video can show you what I mean. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/74302008/98812322-2bf29580-241a-11eb-8cbe-00a72a189389.gif)

**Comment by argyleink** [comment] 2020-11-11 16:30
thank you for reporting, looks like a regression, and a straight forward one to fix! i'll work on this very soon, the tool should be easy to show and hide 👍

**Comment by argyleink** [comment] 2020-11-11 20:12
will be in the next version 0.3.4 which I'll release in the next day or 2 👍

**Closed** 2020-11-11 20:11 UTC
Labels: 🐜 bug

**Comment by JDBem** [comment] 2020-11-11 21:12
Awesome thanks @argyleink! Will this be for both chrome and safari?

**Comment by argyleink** [comment] 2020-11-12 17:29
you know it! 🙂
